import React from 'react'

function Cookie() {
  return (
    <div className="container" style={{marginBottom:'80px'}}>
  {/* <h3 class="progress-one__title">We have the Tools and Expertise <br>
              to help you Succeed online</h3> */}
  <div className="row">
    <div className="col-xl-4 col-lg-4">
      <div className="services-details__left">
        <div
          className="services-details__category"
          style={{ backgroundColor: "unset" }}
        >
          <ul className="services-details__category-box list-unstyled ">
            <li>
              <a href="privacy_policy">Privacy Policy</a>
            </li>
            <li>
              <a href="disclaimer">Disclaimer</a>
            </li>
            <li>
              <a href="terms">Terms and Conditions</a>
            </li>
            <li className="active">
              <a href="cookies">Cookie Policy</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div className="col-xl-8 col-lg-8">
      <div className="progress-one__left">
        <div className="progress-one__progress-box">
          <div data-aos="fade-right">
            <h2
              className="progress-one__progress-box-title"
              style={{ color: "black", fontSize: 43  }}
            >
              COOKIE POLICY
            </h2>
            <div className="progress-levels">
              {/*Skill Box*/}
              <div className="progress-box">
                <div className="inner count-box pt-4">
                  <h4>1. What are Cookies?</h4>
                  <div className="bar pt-2">
                    <p
                      className="services-details__text-1"
                      style={{ color: "black", textAlign: "justify" }}
                    >
                      "cookies" refer to small files that are stored on a user’s
                      computer. They are designed to hold a modest amount of
                      data specific to a particular client and website, and can
                      be accessed either by the web server or the client
                      computer. This allows the server to deliver a page
                      tailored to a particular user, or the page itself can
                      contain some script which is aware of the data in the
                      cookie and so is able to carry information from one visit
                      to the website (or related site) to the next.
                    </p>
                    <p
                      className="services-details__text-1"
                      style={{ color: "black", textAlign: "justify" }}
                    >
                      Please note that cookies are not used to identify you
                      personally or for any purpose other than those described
                      in this Cookie Policy. When you enter TRANS X MARKET
                      website, you accept the use of cookies. To reject the use
                      of cookies, please see the section “Managing cookies”
                      below.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="inner count-box pt-4">
            <h4> 2. Types of cookies and their purpose</h4>
            <div className="bar pt-2">
              <p
                className="services-details__text-1"
                style={{ color: "black", textAlign: "justify" }}
              >
                Generally, cookies can be categorized into two types -
                first-party cookies and third-party cookies. First-party cookies
                are created by the website the user visits, for example, TRANS X
                MARKET, whereas third-party cookies are generated by websites
                from a domain different from TRANS X MARKET.
              </p>
              <p
                className="services-details__text-1"
                style={{ color: "black", textAlign: "justify" }}
              >
                Cookies can stay on your computer or device for varying
                durations. Session cookies are temporary and only exist while
                the browser is open; they are automatically deleted once the
                browser is closed, marking the end of the session. On the other
                hand, persistent cookies continue to remain on your hard drive
                even after closing the browser, until they are deleted by the
                user.
              </p>
              <p
                className="services-details__text-1"
                style={{ color: "black", textAlign: "justify" }}
              >
                The cookies utilized byTRANS X MARKET can be further classified
                into several categories, each serving a distinct purpose:
                <br />
                &nbsp;<b>1. Strictly Necessary Cookies:</b> These are vital for
                ensuring the proper operation of the website and its features.
                <br />
                &nbsp;<b>2. Functionality Cookies:</b> These are employed to
                offer personalized features and to recall your preferences and
                choices regarding the website, such as language and region.
                <br />
                &nbsp;<b>3. Performance Cookies:</b> These are utilized to
                collect statistical data and information on the website's usage,
                identify what appeals most to visitors, and so on, with the aim
                of enhancing the website's functions.
                <br />
                &nbsp;<b>4. Advertising Cookies:</b> These are third-party
                cookies that monitor the online activities of website visitors
                to provide them with pertinent advertisements.
              </p>
            </div>
          </div>
          <div className="inner count-box pt-4">
            <h4> 3. consent and withdrawl</h4>
            <div className="bar pt-2">
              <p
                className="services-details__text-1"
                style={{ color: "black", textAlign: "justify" }}
              >
                you agree withTRANS X MARKET Cookie Policy by continuing to use
                TRANS X MARKET website.
              </p>
            </div>
          </div>
          <div className="inner count-box pt-4">
            <h4> 4. Managing cookies</h4>
            <div className="bar pt-2">
              <p
                className="services-details__text-1"
                style={{ color: "black", textAlign: "justify" }}
              >
                Blocking or removing cookies may lead to the unavailability of
                some features of the website and the loss of any preferences
                that have been set.
              </p>
              <p
                className="services-details__text-1"
                style={{ color: "black", textAlign: "justify" }}
              >
                You have the ability to manage cookies on your computer or
                device by modifying the cookie settings in your browser. This
                allows you to decide whether to accept or reject cookies, or to
                receive notifications of new cookies.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  )
}

export default Cookie
